DELETE http://localhost:5000/api/logout
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczNzIzMjAxNCwianRpIjoiNTU0OWNlZDQtMjAwOS00NGFiLTgxZTAtOWE5NzJjODJmN2Y4IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJnb256YWxleiIsIm5iZiI6MTczNzIzMjAxNCwiZXhwIjoxNzM3MzE4NDE0LCJyb2xlcyI6W10sImFkbWluIjp0cnVlLCJob3NwaXRhbF9pZCI6ImVsIHF1ZSB5byBxdWllcm8ifQ.qoZ0obDBfgkdrt9NK4UXjG5oz2zkVDbBbHp5gT9JDu8
