Actualiza Configuration
---
tags:
- "configuration"
responses:
  200:
    description: Se actualiza Configuration
  401:
    description: Las credenciales proveídas en los datos de login son inválidos
  422:
    description: El access_token no es válido. (Not enough segments, invalid utf-8 chars, etc.)
parameters:
  - in: header
    name: Authorization
    description: Access token
    required: true
    default: Bearer [access_token]
  - name: id
    in: path
    required: true
  - name: body
    in: body
    schema:
      $ref: "#/definitions/ConfigurationPut"
definitions:
    ConfigurationPut:
        type: "object"
        properties:
            id:
                type: "int64"
            name:
                type: "string"
            value:
                type: "string"
            code:
                type: "string"
        example:
            id: 18
            name: Lorem ipsum dolor sit amet
            value: Lorem ipsum dolor sit amet
            code: Lorem ipsum dolor sit amet
